name: them
description: Ứng dụng Thèm - Chia sẻ trải nghiệm qua pin location và livestream

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Handle errors
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.1.2
  
  # Navigation
  go_router: ^10.1.2
  
  # Maps & Location (sẽ thêm khi phát triển phần map)
  # mapbox_gl: ^0.16.0
  # geolocator: ^10.0.0
  # geocoding: ^2.1.0
  
  # Authentication (sẽ thêm khi phát triển phần auth)
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.7.3
  # google_sign_in: ^6.1.4
  # flutter_facebook_auth: ^6.0.1
  flutter_secure_storage: ^8.0.0
  
  # Networking
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # UI
  flutter_native_splash: ^2.3.2
  cupertino_icons: ^1.0.5
  
  # Internationalization
  intl: ^0.19.0
  
  # Utilities
  logger: ^1.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^2.0.2
  
  # Code Generation
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Add assets here
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
    - .env
    
  # Add fonts here
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #         weight: 300

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

# Internationalization settings
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/app/localization